### ISSUE TITLE
Turn tracks?

### ISSUE THREAD

**Issue by msopata95** [hsanjuan/go-dcc#1]
How would one implement turn tracks when using go-dcc/dccpi? I see everything for locomotives, but nothing about turn tracks.

**Comment by hsanjuan** [comment]
hi, sorry for my lack of knowledge, but can you define what a "turn track" is?

**Comment by msopata95** [comment]
Something like this:

http://www3.towerhobbies.com/cgi-bin/wti0001p?&I=LXJGA0&P=FR&gclid=Cj0KEQiAk5zEBRD9lfno2dek0tsBEiQAWVKyuAX7k48DXOknLiID7pavWsthdj0nL_hmTIOIiK8zbAYaAgJH8P8HAQ

**Comment by hsanjuan** [comment]
Ah right. Yes, I think these devices are run by DCC decoders which simply support F1-F4 functions.

Therefore, you can use `Locomotive` with the right address to control them with the current code. I will think about  providing a `Device` type for such thing to be more elegant in the future.

**Comment by msopata95** [comment]
Wonderful, thank you!
