### ISSUE TITLE
Use as library

### ISSUE THREAD

**Issue by ragadeeshu** [hsanjuan/go-dcc#3]
Hi, I'm currently writing a custom frontend for dccpi, but the python version hogs way too much resources from the pi, and hence I turned my eyes in this direction. However, I only see the possibility to use go-dcc as a standalone app, not as a library? A callable exported library would be really nice to have, and it would allow interfacing with python and other custom fontends. I'm happy to help, but I'm alas very new to go.

**Comment by hsanjuan** [comment]
Hi, you can use it as a library:

https://godoc.org/github.com/hsanjuan/go-dcc

The `dccpi` command is a cli-frontend to the go-dcc library (https://github.com/hsanjuan/go-dcc/blob/master/dccpi/dccpi.go)

**Comment by ragadeeshu** [comment]
Hello, thanks, and sorry. As stated, I'm very new to go. Is this api callable from python? What is the install path of the module to import?

**Comment by hsanjuan** [comment]
Unless there is some funky python magic to do such thing, this is a Go API usable from Go.

**Comment by ragadeeshu** [comment]
I was thinking something along these lines

**Comment by hsanjuan** [comment]
Yes, you would need to wrap the library with a `main` module that exports what you're interested in as explained in that post and then use that from python.
