### ISSUE TITLE
Setup tips

### ISSUE THREAD

**Issue by jeffeb3** [hsanjuan/go-dcc#5]
Sorry for making this an issue. I'm really just hoping to have a conversation with you about this project. If you would like to continue this conversation outside of the github issues, my email is jeffeb3 at gmail.com.

I am very excited about this dcc library. I am a software developer by day and I work with 3D printers, CNC machines, arduinos, raspberry pi's, etc by night. My dad recently started pulling out his model train stuff again, and my 3 year old son is a huge fan. My long term goals for this project is to set up simple high-level controls for my son. Things like "put the caboose in track 5", "add cars 1,2,3", and "add the caboose". 

We are starting with a bunch of gear from the late 90s and I have been just deep diving into everything that exists now that didn't when I got started. I am hooking up some relays to the track "turnouts" (the Y tracks), connecting them to a pi. Then I want to start controlling our older engines with the pi, so I bought two H bridge controllers and I hope at least one of them will work for that.

Next is going to be using go-dcc encode commands on the track, and upgrading one or more of our engines to DCC (I think they are easy to upgrade, youtube makes it look easy, anyway). I have plans for a small 7" touchscreen controller to be the interface to the toddler. I have no experience with go, but I am really intrigued. The things I've read have made me very interested.

If you don't mind me asking for your advice, do you think a motor controller like this one would work for the DCC booster? I'm not excited about building my own, especially if $10 can get me what I need:

https://www.robotshop.com/en/l298-dual-h-bridge-dc-motor-controller.html

The other question I had is: Have you considered doing the bit banging in a micro controller, like an arduino nano, with a UART connection to the pi for higher level command and control? The CPU usage on the pi would go way down, presumably. I haven't gone through your go-dcc code yet, but reading through the DCC specs, it seems like an enormous amount of time is spent just doing the '1' message waiting for something to do, which is probably pretty intensive.

Thanks for publishing your work. This is very interesting, and I think it will be very fun to use.

**Comment by jeffeb3** [comment]
Yeah, this board will definitely be an experiment. This board is also missing the external booster capacitors, which appear to help it create a sharp, quick edge. The timing on it might be a problem. The board you have also has that current sensing resistor. I'm not sure if that's to help the power supply, or the board. 

The other big issue is that it has 4 pins, basically each one controls one of the outputs (A+, A-, B+, B-), where your logic is built to do DIR and PWM pins. I suppose I can replace the Driver object with something that will just flip both pins instead of flipping the DIR pin.

**Comment by MvonR** [comment]
Hello ,
the go-dcc should be my solution to digtize my modell-rail.
But my current problem is that I can't get the software to work. 
After the start of : "go run dccpi.go" comes the message: "Cannot load configuration, Using emty one".
Have one of you any ideas where the error is? My knowledge of GO is limited. Do I have to install some configuration-sw in front of starting that Main-Program?

**Comment by hsanjuan** [comment]
Hi @MvonR : Follow the instructions: https://github.com/hsanjuan/go-dcc#installation there it mentions how to install the program and how the configuration looks like.

**Comment by MvonR** [comment]
Hello,
I did that 5-6 times:
The dccpi application allows to control locomotives and other DCC devices. Execute it and you will be taken to the dccpi console.
What does "Execute it" means?

**Comment by MvonR** [comment]
…
I do these steps:
- install golang-go
- simply run:  2 lines
- Building Sources: 3 lines
All steps runs fine.
Then I start the compiled dccpi app

Result:  "Cannot load configuration, Using emty one"
I have a Raspberry 3B+
